# Generated by Django 4.2.6 on 2024-03-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.TextField(max_length=100)),
                ('descricao', models.TextField(max_length=350)),
                ('locado', models.BooleanField()),
                ('comprado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cotacao', models.DateField()),
                ('valor_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fornecedores', models.ManyToManyField(to='cliente.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.item')),
            ],
        ),
    ]
