# Generated by Django 5.0.3 on 2024-04-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_fornecedor_cliente_ddd_cliente_image_cliente_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.job')),
            ],
        ),
    ]
