# Generated by Django 5.0.3 on 2024-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_fornecedor_item_cotacao'),
    ]

    operations = [
    ]
