# Generated by Django 5.0.3 on 2024-03-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='fornecedores',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='item',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ddd',
            field=models.CharField(default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='cliente',
            name='site',
            field=models.TextField(default=1, max_length=58),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
