# Generated by Django 5.0.3 on 2024-04-15 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_itemjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='prazo_intalacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
