# Generated by Django 5.0.3 on 2024-04-16 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_item_fornecedor_principal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fornecedor_principal',
        ),
        migrations.AddField(
            model_name='job',
            name='itens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='cliente.item', verbose_name='Itens'),
        ),
    ]
