# Generated by Django 5.0.3 on 2024-04-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_item_fornecedor_principal_job_itens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='uf',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='uf',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='uf',
            field=models.TextField(max_length=2),
        ),
    ]
