# Generated by Django 5.0.3 on 2024-03-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_cotacao_fornecedores_remove_cotacao_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(default='none', upload_to='images/'),
        ),
    ]
