# Generated by Django 5.0.3 on 2024-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_itemfornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfornecedor',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemjob',
            name='quantidade_solicitada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
