# Generated by Django 4.2.6 on 2024-03-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.TextField(max_length=88)),
                ('complemento', models.TextField(max_length=88)),
                ('municipio', models.TextField(max_length=88)),
                ('uf', models.TextField(max_length=88)),
                ('ddd', models.CharField(default='XX', max_length=2)),
                ('telefone', models.CharField(max_length=9)),
            ],
        ),
    ]
