# Generated by Django 5.0.3 on 2024-04-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_uf_alter_fornecedor_uf_alter_job_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='image',
        ),
    ]
