# Generated by Django 5.0.3 on 2024-04-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_remove_item_data_cotacao_remove_item_descricao_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemjob',
            name='quantidade_solicitada',
        ),
        migrations.AddField(
            model_name='fornecimento',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='item',
            field=models.ManyToManyField(through='cliente.ItemJob', to='cliente.item'),
        ),
        migrations.AddField(
            model_name='job',
            name='quantidade_item',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
