# Generated by Django 5.0.3 on 2024-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_remove_itemjob_quantidade_solicitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='documento',
            field=models.FileField(default='none', upload_to='documentos/'),
        ),
    ]
